### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [javerous/AsmHelper#1]
looks like a nice tool, congrats! do you have any screenshots to share?

keep it up, cheers!

**Comment by javerous** [comment]
Hello Anh ! Thank you. 

It's a very little tool, used for very specific usage, but very helpful for my needs. I used to work with `otool` & `as` to do the work, but it was a little bit too artisanal and uncertain, so I eventually switched to your very convenient frameworks (and thank you for this incredible work !).

I saw you added it in your Showcase : thank you too for that :)

I will make it evolve yes, and I think we can say there is a big potential of evolution…

![asmhelper](https://cloud.githubusercontent.com/assets/1971659/25063793/e111a5b0-21ed-11e7-97c5-62fe9171920a.png)

**Comment by aquynh** [comment]
Wow, this looks really nice, thanks for the screenshot.

Cheers,
Quynh
