### ISSUE TITLE
Building on Mojave, xcode11

### ISSUE THREAD

**Issue by feedface** [javerous/AsmHelper#2]
I downloaded capstone/keystone source. Copied capstone headers to the required location.
I actually also used the fork from zhkl0228.
Same issue during linking:
```
Undefined symbols for architecture x86_64:
  "EVM_opcode(char const*)", referenced from:
      _ks_asm in libkeystone.a(ks.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My apologies if this is obvious, but could you provide ideas on how to resolve? Keystone compiles just fine.

**Comment by javerous** [comment]
Hi ! I never see this problem before, and I don't have Mojave to test :(

Did you try something as simple as :
- `git clone https://github.com/javerous/AsmHelper.git`
- `cd AsmHelper`
- `git submodule update --init --recursive`
- Then build the Xcode project ?

**Comment by feedface** [comment]
Thanks. I've just tried it on my new mac. No issues. I suspect file damage due to failing SSD on my old mac.
